import type { DistrictConfig, LetterData, TemplatePreset } from '../types/letter'

export const DEFAULT_DISTRICT_CONFIG: DistrictConfig = {
  districtName: 'CAÑON CITY SCHOOLS',
  districtSubtitle: 'SCHOOL DISTRICT FREMONT RE-1',
  addressLine1: '101 North 14th Street',
  cityStateZip: 'Cañon City, Colorado 81212',
  phone: '(719) 276-5700',
  fax: '(719) 276-5739',
  hrEmail: 'kimberly.strickengloss@canoncityschools.org',
  hrPhone: '719-276-5701',
  missionStatement:
    '“The Cañon City School District is future-focused, providing innovative educational opportunities to successfully prepare all students to meet any challenge they may face,”',
  adminStaff: [
    { id: '1', name: 'ADAM HARTMAN', title: 'Superintendent of Schools' },
    { id: '2', name: 'DAN COPPA', title: 'Director of Technology' },
    { id: '3', name: 'JAMIE DAVIS', title: 'Director of Human Resources' },
    { id: '4', name: 'GLENN HAYES', title: 'Chief Financial Officer' },
    { id: '5', name: 'SCOTT MORTON', title: 'Director of Operations' },
    { id: '6', name: 'TIM RENN', title: 'Director of Special Services' },
    { id: '7', name: 'GARRETT OLGUIN', title: 'Director of Curriculum & Assessment' },
  ],
  defaultSignerName: 'Jamie Davis',
  defaultSignerTitle: 'Director of Human Resources',
  defaultTypistInitials: '/ks',
  defaultCc: 'Cc: personnel file',
}

export const SAMPLE_PRESETS: TemplatePreset[] = [
  {
    id: 'certified-standard',
    name: 'Certified',
    description: 'Licensed Staff Placement (Lane, Step, Base Salary)',
    letter: {
      id: 'cert-1',
      type: 'certified',
      letterDate: 'August 24, 2026',
      boardMeetingDate: 'August 24, 2026',
      schoolYear: '2026-2027',
      recipientFirstName: '',
      recipientLastName: '',
      streetAddress: '',
      city: 'Cañon City',
      state: 'CO',
      zip: '81212',
      positionTitle: 'Part-time Lead Counselor',
      location: 'District-wide',
      certified: {
        lane: 'MA+48',
        step: '23',
        baseSalary: '$21,031.50',
        startDate: 'September 1, 2026',
        isPartTime: true,
        fteText: 'Part-time',
      },
      signerName: 'Jamie Davis',
      signerTitle: 'Director of Human Resources',
      typistInitials: '/ks',
      ccLine: 'Cc: personnel file',
      signatureType: 'authentic',
    },
  },
  {
    id: 'classified-standard',
    name: 'Classified',
    description: 'Classified Support Placement (Classification, Level, Base Wage)',
    letter: {
      id: 'class-1',
      type: 'classified',
      letterDate: 'August 24, 2026',
      boardMeetingDate: 'August 24, 2026',
      schoolYear: '2026-2027',
      recipientFirstName: '',
      recipientLastName: '',
      streetAddress: '',
      city: 'Cañon City',
      state: 'CO',
      zip: '81212',
      positionTitle: 'School Health Technician',
      location: 'Cañon City High School',
      classified: {
        classification: 'P6',
        level: 'E',
        baseWage: '$19.67',
        wageUnit: 'hour',
        startDate: 'August 20, 2026',
      },
      signerName: 'Jamie Davis',
      signerTitle: 'Director of Human Resources',
      typistInitials: '/ks',
      ccLine: 'Cc: personnel file',
      signatureType: 'authentic',
    },
  },
  {
    id: 'classified-stipend',
    name: 'Classified (w/ Stipend)',
    description: 'Classified Support Placement with Center-Based Stipend',
    letter: {
      id: 'class-2',
      type: 'classified',
      letterDate: 'August 24, 2026',
      boardMeetingDate: 'August 24, 2026',
      schoolYear: '2026-2027',
      recipientFirstName: '',
      recipientLastName: '',
      streetAddress: '',
      city: 'Penrose',
      state: 'CO',
      zip: '81240',
      positionTitle: 'Significant Needs (SSN) Special Education Paraprofessional',
      location: 'Cañon City Middle School',
      classified: {
        classification: 'P5',
        level: 'D',
        baseWage: '$18.56',
        stipendText: 'Plus a center-based stipend of $2,000',
        startDate: 'August 17, 2026',
      },
      signerName: 'Jamie Davis',
      signerTitle: 'Director of Human Resources',
      typistInitials: '/ks',
      ccLine: 'Cc: personnel file',
      signatureType: 'authentic',
    },
  },
  {
    id: 'transfer-standard',
    name: 'Transfer',
    description: 'Approval of Transfer in Position & Hours',
    letter: {
      id: 'trans-1',
      type: 'transfer',
      letterDate: 'August 24, 2026',
      boardMeetingDate: 'August 24, 2026',
      schoolYear: '2026/2027',
      recipientFirstName: '',
      recipientLastName: '',
      streetAddress: '',
      city: 'Cañon City',
      state: 'CO',
      zip: '81212',
      positionTitle: 'Crossing Guard / Noon Aide',
      location: 'Washington Elementary School',
      transfer: {
        newPosition: 'Crossing Guard / Noon Aide',
        newLocation: 'Washington Elementary School',
        transferDescription:
          'your transfer in position and hours back to Crossing Guard / Noon Aide at Washington Elementary School',
        effectiveDate: 'August 12, 2026',
      },
      signerName: 'Jamie Davis',
      signerTitle: 'Director of Human Resources',
      typistInitials: '/ks',
      ccLine: 'Cc: personnel file',
      signatureType: 'authentic',
    },
  },
  {
    id: 'resignation-standard',
    name: 'Resignation',
    description: 'Formal Board Acknowledgement and Acceptance of Resignation',
    letter: {
      id: 'resig-1',
      type: 'resignation',
      letterDate: 'August 24, 2026',
      boardMeetingDate: 'August 24, 2026',
      schoolYear: '2026-2027',
      recipientFirstName: '',
      recipientLastName: '',
      streetAddress: '',
      city: 'Cañon City',
      state: 'CO',
      zip: '81212',
      positionTitle: '4th Grade Teacher',
      location: 'Harrison Elementary School',
      resignation: {
        position: '4th Grade Teacher',
        location: 'Harrison Elementary School',
        effectiveDate: 'August 15, 2026',
        customAppreciation:
          'Thank you for your dedicated service and commitment to the students and families of Cañon City Schools. We wish you the very best in all of your future personal and professional endeavors.',
      },
      signerName: 'Jamie Davis',
      signerTitle: 'Director of Human Resources',
      typistInitials: '/ks',
      ccLine: 'Cc: personnel file',
      signatureType: 'authentic',
    },
  },
  {
    id: 'retirement-standard',
    name: 'Retirement',
    description: 'Board approval of request for retirement with spring celebration',
    letter: {
      id: 'retire-1',
      type: 'retirement',
      letterDate: 'August 24, 2026',
      boardMeetingDate: 'August 24, 2026',
      schoolYear: '2026-2027',
      recipientFirstName: '',
      recipientLastName: '',
      streetAddress: '',
      city: 'Cañon City',
      state: 'CO',
      zip: '81212',
      positionTitle: 'Elementary Teacher',
      location: 'Washington Elementary School',
      retirement: {
        position: 'Elementary Teacher',
        location: 'Washington Elementary School',
        effectiveDate: 'June 5, 2026',
        includeRemainderOfYear: false,
        yearsOfService: '25',
        celebrationText:
          'We will be holding a celebration for retirees in April, 2027. Please watch for more detailed information to be shared closer to the event.',
      },
      signerName: 'Jamie Davis',
      signerTitle: 'Director of Human Resources',
      typistInitials: '/ks',
      ccLine: 'Cc: personnel file',
      signatureType: 'authentic',
    },
  },
  {
    id: 'retirement-remainder',
    name: 'Retirement (Remainder of Year)',
    description: 'Retirement effective for remainder of school year with May event',
    letter: {
      id: 'retire-2',
      type: 'retirement',
      letterDate: 'August 24, 2026',
      boardMeetingDate: 'August 24, 2026',
      schoolYear: '2025/2026',
      recipientFirstName: '',
      recipientLastName: '',
      streetAddress: '',
      city: 'Cañon City',
      state: 'CO',
      zip: '81212',
      positionTitle: 'High School Counselor',
      location: 'Cañon City High School',
      retirement: {
        position: 'High School Counselor',
        location: 'Cañon City High School',
        effectiveDate: 'May 29, 2026',
        includeRemainderOfYear: true,
        remainderYearText: 'for the remainder of the 2025/2026 School Year.',
        yearsOfService: '20',
        celebrationText:
          'We will be holding a celebration for retirees from 5:00 pm to 7:30 pm on Tuesday, May 5th, 2026. Please watch for more detailed information to be shared closer to the event.',
      },
      signerName: 'Jamie Davis',
      signerTitle: 'Director of Human Resources',
      typistInitials: '/ks',
      ccLine: 'Cc: personnel file',
      signatureType: 'authentic',
    },
  },
]

export const DEFAULT_NEW_LETTER = (type: LetterData['type'] = 'certified'): LetterData => {
  const base: LetterData = {
    id: 'letter-' + Date.now(),
    type,
    letterDate: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    }),
    boardMeetingDate: new Date().toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric',
    }),
    schoolYear: '2026-2027',
    recipientFirstName: '',
    recipientLastName: '',
    streetAddress: '',
    city: 'Cañon City',
    state: 'CO',
    zip: '81212',
    positionTitle: '',
    location: '',
    signerName: 'Jamie Davis',
    signerTitle: 'Director of Human Resources',
    typistInitials: '/ks',
    ccLine: 'Cc: personnel file',
    signatureType: 'authentic',
  }

  if (type === 'certified') {
    base.certified = {
      lane: '',
      step: '',
      baseSalary: '',
      startDate: '',
      isPartTime: false,
    }
  } else if (type === 'classified') {
    base.classified = {
      classification: '',
      level: '',
      baseWage: '',
      stipendText: '',
      wageUnit: 'hour',
      startDate: '',
    }
  } else if (type === 'transfer') {
    base.transfer = {
      newPosition: '',
      newLocation: '',
      transferDescription: '',
      effectiveDate: '',
    }
  } else if (type === 'resignation') {
    base.resignation = {
      position: '',
      location: '',
      effectiveDate: '',
      customAppreciation:
        'Thank you for your dedicated service and commitment to the students and families of Cañon City Schools. We wish you the very best in all of your future endeavors.',
    }
  } else if (type === 'retirement') {
    base.retirement = {
      position: '',
      location: '',
      effectiveDate: '',
      includeRemainderOfYear: false,
      remainderYearText: 'for the remainder of the 2026-2027 School Year.',
      yearsOfService: '',
      celebrationText:
        'We will be holding a celebration for retirees in April, 2027. Please watch for more detailed information to be shared closer to the event.',
    }
  }

  return base
}
